### ISSUE TITLE
Comment for IPs

### ISSUE THREAD

**Issue by BBcan177** [Hestat/minerchk#1]
For **minerlist.txt** and **minerlist-all.txt**, would you consider adding a "**#**" before the IPs?

This would allow for pfBlockerNG to parse these feeds and collect the Domains names and consider the IP as a comment as that format would follow most other domain based feed format.

Would you also consider adding a new IP feed for these IPs?

Also noticed the **hostlist.txt**  has "**xmr-eu1[.]nanopool[.]org**"  but the "**minerlist-all**" 
has only "**xmr-eu[.]nanopool[.]org**"? Was just an observation.

Thanks for providing these Feeds!

**Comment by ZeroDot1** [comment]
That's a good idea.

**Comment by Hestat** [comment]
Thanks for the feedback, I've decided to keep just the minerlist-all for ease of updates. I've added the # commenting for proper parsing. Let me know if you see other improvements or slip ups.

I've added xmr-eu1[.]nanopool[.]org to the minerlist-all as well.
