### ISSUE TITLE
More pools to add

### ISSUE THREAD

**Issue by ZeroDot1** [Hestat/minerchk#2]
Have a look at the CoinBlockerLists, you can find more pools inside.
https://github.com/ZeroDot1/CoinBlockerLists
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts

**Comment by Hestat** [comment]
Hello, been a little while to get around to this with work on other projects. I absolutely love the list you have put together for blocking, and think it works great in a lan network or endpoint blocklist. Minerchk on the other hand is focused on Webservers which can present some issues with adding all possible mining related domains. One specific case is if the mining pool is using cloudflare, and the webserver we are protecting is also using cloudflare, this could then block legitimate traffic. 

I most certainly use your list as an amazing resource and heartily recommend it to network admins and endpoint block listing. 

Keep up the great work!

**Comment by ZeroDot1** [comment]
Thank you, I hope this list helps to protect many computers.
I have created a homepage on which you can find some additional information. 
https://zerodot1.github.io/CoinBlockerListsWeb/downloads.html
